Django/blog/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

urlpatterns = [
    path('', views.PostList.as_view()),
    path('<int:pk>/', views.PostDetail.as_view()),

    # 만약에 지금 이게 붙어 있으면, pk라는 변수에 담아서 single_post_page() 함수로 넘기겠다는 말임.
    # path('<int:pk>/', views.single_post_page),
    # 함수명 꼭 index가 아니어도 상관없습니다. 함수명을 소문자로 만드는 습관은 있다. # 여기서는 지금 /blog/ 뒤에 아무것도 없으면
    # path('', views.index),
    # view에 index 함수 불러 오겠다는 말이고,
]

Django/do_it_django_prj/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.conf import settings  # 이거를 하는 이유가, static 파일이랑 setting 파일을 사용해야하니까,
from django.conf.urls.static import static


urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    # 이게 첫 메인 화면인거지, path 가 공백이니까 8000포트 url 그대로
    path('', include('single_pages.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)  # 이미지 URL 등록한거임

Django/single_pages/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    path('about_me/', views.about_me),
    path('', views.landing),
]

Django/blog/models.py
from django.db import models
from django.contrib.auth.models import User
import os

# 여기에 Post 모델을 정의하고, admin.py에 코드를 추가하면 된다.


class Category(models.Model):
    # unique=True로 만들면 동일한 name을 갖는 카테고리를 또 만들 수 없음.
    name = models.CharField(max_length=50, unique=True)
    # slug 필드를 만들때 사용한 SlugField는 사람이 읽을 수 있는 텍스트로 고유 URL을 만들고 싶을때 사용함.
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
    # 원래 slugField 한글 지원 안하는데, allow_unicode=True로 설정해 한글로도 만들 수 있는거임.

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class Post(models.Model):
    title = models.CharField(max_length=30)  # 이거는 문자 담는 필드,
    content = models.TextField()  # 길이 제한이 없도록 TextField 만들었고,

    # 이거 지금 후크 텍스트로 그 워싱턴 포스트 같은 웹 사이트가 제목 아래에 드는 소제목
    hook_text = models.CharField(max_length=100, blank=True)

    # blank=True라고 하는 이유가, 이 필드가 필수 필드가 아니란거지, blank=True라고 안하면 왜 안채웠냐고 뭐라하거든,
    head_image = models.ImageField(
        upload_to='blog/images/%Y/%m/%d/', blank=True)
    # 이제 이미지를 저장할 경로를 model에서 구현 하는 부분임. 연도 폴더, 월 폴더, 일 폴더까지 내려간 위치
    # 근데 이게 빨라서 하는거지, 연도, 시간 이렇게 폴더 플로우는 비교적 빠른데, 한 폴더에 다 넣으면 찾는데 서버가 너무 힘들어 하거든,

    file_upload = models.FileField(
        upload_to='blog/files/%Y/%m/%d/', blank=True)  # 이거 이제 파일 필드임. # 파일도 올릴 수 있도록 모델 만든거지
    # 처음 레코드 생성될떄 현지 시각이 자동으로 저장되게 하는게 auto_now_add
    created_at = models.DateTimeField(auto_now_add=True)
    # auto_now 는 설정해서 다시 저장될때 그 시각 저장.
    updated_at = models.DateTimeField(auto_now=True)

    # 이 포스트의 작성자가 데이터베이스에서 삭제 되었을 떄 이 포스트도 같이 삭제한다.
    # author = models.ForeignKey(User, on_delete=models.CASCADE)
    # 이 포스트의 작성자가 데이터 베이스에서 삭제되었을때 작성자명을 빈칸으로 둔다는 말임.
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    # 여기 author은 User 라는 원래 제공되는 class 사용한거고,
    category = models.ForeignKey(
        Category, null=True, blank=True, on_delete=models.SET_NULL)
    # 여기 카테고리는 위에 우리가 class 직접 만들었잖슴.

    def __str__(self):
        # 이게 지금 해당 포스트 pK값이랑, 해당 포스트의 title 값임. 원래 장고 모델 만들면 자동으로 pk값이 주어지거든?
        return f'[{self.pk}]{self.title} :: {self.author}'
        # 처음 생성하면 pk1 주어지는거고, 그 다음은 2고 이런거임, 그래서 이렇게하면 포스트 번호랑, 포스트 제목이랑 나오게 된다.

    def get_absolute_url(self):
        # 여기서 잘 이해안가는데, 일단 이게 get_absoulte_url()함수를 만드는 과정임.
        # 이렇게 하면, 리턴 주면서 저기 blog/1/ 이나 blog/2/ 로 들어갈 수 있다.
        return f'/blog/{self.pk}/'

    # 이 부분이 파일 이름 downloat해서 보여질 수 있도록 설계하는 부분

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]

Django/single_pages/models.py
from django.db import models

# Create your models here.

Django/blog/views.py
from .models import Post, Category
from django.shortcuts import render
from django.views.generic import ListView, DetailView


class PostList(ListView):  # 이게 지금 list view가 레코드 목록 형태 보여줄때 사용하는거고,
    model = Post
    # 이렇게 안하고, 그냥 저 템플릿 이름 바꿔도 괜찮은데 난 이게 편해서 이름 지정해줌
    template_name = 'blog/index.html'
    ordering = '-pk'  # 이거는 FCV 방식에서 order_by(-pk)랑 똑같은 거임.

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data()
        # 모든 카테고리를 들고와서 'categories'라는 이름의 키에 연결해 담는거임.
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(
            category=None).count()

        return context


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        # 모든 카테고리를 들고와서 'categories'라는 이름의 키에 연결해 담는거임.
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(
            category=None).count()

        return context

    template_name = 'blog/single_post_page.html'

# 이거는 FCV 방식이라서  CBV 방식으로 하기 위해서 주석 처리함.
# def index(request):
#     # 이런 방식으로 views.py에서 데이터베이스에 쿼리를 날려서 원하는 레코드를 가져올 수 있다.
#     posts = Post.objects.all().order_by('-pk')
#     # 여기서 쿼리는 데이터 베이스 데이터를 가져오거나 수정, 삭제하는 등의 행위를 하기 위한 요청입니다. 쿼리 명령어는 all()외에도
#     # filter(), order_by(), create(), delete() 등으로 다양하다. 이 명령어들은 뒤에서 배운다.

#     return render(  # 장고가 기본적으로 제공하는 render함수로서, 템플릿 폴더에서, blog 폴더의 index.html을 찾아서 방문자한테 보여준다.
#         request,
#         'blog/index.html',
#         {
#             'posts': posts,  # 지금 이걸로 posts 를 index html에 뿌려주고 있음.
#         }
#     )


# def single_post_page(request, pk):
#     post = Post.objects.get(pk=pk)  # 지금 괄호 안의 조건을 만족하는 Post 레코드를 가져오라는 뜻입니다.

#     return render(
#         request,
#         'blog/single_post_page.html',
#         {
#             'post': post,
#         }
#     )

Django/single_pages/views.py
from django.http import request
from django.shortcuts import render


def landing(request):
    return render(
        request,
        'single_pages/landing.html'
    )


def about_me(request):
    return render(
        request,
        'single_pages/about_me.html'
    )

Django/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %} <!--지금 이 부분이 Static 부분 사용하겠다고 선언한 부분임.-->
<html>
    <head>
        <title>{% block head_title %}Blog{% endblock %}</title>
        <link href="{% static 'blog/bootstrap/bootstrap.min.css' %}" rel="stylesheet" media="screen">
        <!-- <style>
            nav {background-color: darkgreen; font-size: 150%; text-align: center;}
            nav a { color: gold;}
        </style> -->
        <script src="https://kit.fontawesome.com/eb0e7c00c5.js" crossorigin="anonymous"></script>
    </head>
    
        <body style="margin-top: 60px;">
            {% include 'blog/navbar.html' %}

            <div class="container my-3">
                
                <div class="row">
                    <div class="col-md-8 col-lg-9" id="main-area">
                        {% block main_area %}
                        {% endblock %}
                    </div>
                

                    <div class="col-md-4 col-lg-3">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <div class="input-group">
                                <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                            </div>
                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card mb-4" id="categories-card">
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">
                                <!-- <div class="col-sm-6"> -->
                                    <ul>
                                        {% for category in categories %}
                                        <li><a href="{{ category.get_absolute_url }}">{{ category }}({{ category.post_set.count }})</a></li>
                                        {% endfor %}
                                        <li><a href="/blog/category/no_category/">미분류({{ no_category_post_count }})</a></li>
                                    </ul>
                                <!-- </div> -->
                                <!-- <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!">JavaScript</a></li>
                                        <li><a href="#!">CSS</a></li>
                                        <li><a href="#!">Tutorials</a></li>
                                    </ul> -->
                                <!-- </div> -->
                            </div>
                        </div>
                    </div>
                    </div>

                </div>
            </div>
            {% include 'blog/footer.html' %}
            <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
        </body>
</html>

Django/blog/templates/blog/footer.html
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">
        Copyright &copy; Django project 2021</p>
    </div>
</footer>

Django/blog/templates/blog/index.html
{% extends 'blog/base.html' %}
    {% block main_area %}
    <div class="col-md-8 col-lg-9" id="main-area">
        <h1>Blog</h1>
        {% if post_list.exists %} <!--post_list에 포스트가 있다면 실행-->
        {% for p in post_list %}
            <!-- Blog post-->
            <div class="card mb-4" id="post--{{ p.pk }}">
                {% if p.head_image %}
            <a href="#!"><img class="card-img-top" src="{{ p.head_image.url }}" alt="{{ p }} head image" /></a> <!--image 불러오는거임-->
                {% else %} <!-- 이미지 없어도 할 수 있도록 alt 보여주고,-->
                <img class="card-img-top" src="https://picsum.photos/seed/{{ p.id }}/600/300" alt="random_image"> <!--이게 만약에 위에 안먹을때 랜덤 이미지 만들어주는거임-->
                                        <!--이게 seed로 id 즉 pk 값으로 고정하는거임 -->
                {% endif %}
                <div class="card-body">
                    {% if p.category %}
                    <span class="badge badge-secondary float-right">{{ p.category }}</span>
                    {% else %}
                    <span class="badge badge-secondary float-right">미분류</span>
                    {% endif %}
                    <h2 class="card-title h4">{{ p.title }}</h2>
                {% if p.hook_text %}
                    <h5 class="text-muted">{{ p.hook_text }}</h5> <!--text muted 하는 이유가 그냥 연하게 할려고-->
                {% endif %}
                <p class="card-text">{{ p.content | truncatewords:45 }}</p> <!-- 45개 단어만 출력하도록 truncatewords 씀.-->
                <a href="{{ p.get_absolute_url }}" class="btn btn-primary">Read more &rarr;</a>
            </div>
          
            <div class="card-footer text-muted">
                Posted on {{ p.created_at }} by
                <a href="#">{{ p.author | upper }}</a>
            </div>
        </div>
        {% endfor %}
        {% else %}
            <h3>아직 게시물이 없습니다. </h3>
        {% endif %}
            <!-- Pagination-->
    <ul class="pagination justify-content-center mb-4">
        <li class="page-item">
            <a class="page-link" href="#">&larr; Older</a>
        </li>
        <li class="page-item disabled">
            <a class="page-link" href="#">Newer &rarr;</a>
        </li>
    </ul>
</div>
{% endblock %}
    

Django/blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container">
    <a class="navbar-brand" href="/">Django Project</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/blog/">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about_me/">About_me</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal">loginModal</a>
        </li>
      </ul>

        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">Log In</a>
          </li>

        </ul>
    </div>
  </nav>

  <!-- Modal -->
  <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="loginModalLabel"><i class="fas fa-sign-in-alt"></i>&nbsp Log In</h5> <!-- &nbsp는 간격 띄워주는거임.-->
        <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-6">
                    <button type="button" class="btn btn-outline-success btn-block btn-sm"><i class="fab fa-google"></i>&nbsp&nbsp Log in with Google</button>
                    <button type="button" class="btn btn-outline-success btn-block btn-sm"><i class="far fa-envelope"></i>&nbsp&nbsp Log in with E-mail</button>
                </div>
                <div class="col-md-6">
                    <button type="button" class="btn btn-outline-success btn-block btn-sm"><i class="far fa-envelope"></i>&nbsp&nbsp Sign Up with E-mail</button>
                </div>

                </div>
            </div>    
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
    </div>
    </div>
</div>

Django/blog/templates/blog/single_post_page.html
{% extends 'blog/base.html'%}
{% block head_title %}
    {{ post.title }} - Blog
{% endblock %}

{% block main_area %}
    <div>
        <div id="post-area" style=" margin-top: 50px; ">
            {% if post.category %}
                <span class="badge badge-secondary float-right">{{ post.category }}</span>
            {% else %}
                <span class="badge badge-secondary float-right">미분류</span>
            {% endif %}
                <!-- Post title-->
                <h1 class="fw-bolder mb-1">{{ post.title }}</h1>
                <h5 class="text-muted">{{ post.hook_text }}</h5>
                <!-- Author-->
                <p>
                <div class="text-muted fst-italic mb-2"> by <a href="#">{{ post.author | upper }}</a></div>
                </p>
                <hr>
                <!-- Date/Time -->
                    <p>{{ post.created_at }}</p>
                <hr>
                </header>
            <!-- Preview image figure-->
            {%if post.head_image %}
            <figure class="mb-4"><img class="img-fluid rounded" src="{{ post.head_image.url }}" alt="{{ post.title }} head_image" /></figure>
            {% else %}
            <img class="img-fluid rounded" src="https://picsum.photos/seed/{{ post.id }}/600/300" alt="random_image"> <!--이게 만약에 위에 안먹을때 랜덤 이미지 만들어주는거임-->
            {% endif %}
            <!--이게 seed로 id 즉 pk 값으로 고정하는거임 -->
                <hr/>
            <!-- Post content-->
            <section class="mb-5">
                <p>{{ post.content }}</p> 
                <!-- 파일 다운로드 하는 부분 -->
                {% if post.file_upload %}
                <a href="{{ post.file_upload.url }}" button type="button" class="btn btn-light">Download:
        
                {% if post.get_file_ext == 'csv' %}
                    <i class="fas fa-file-csv"></i>
                {% elif post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
                    <i class="far fa-file-excel"></i>
                {% elif post.get_file_ext == 'docx' or post.get_file_ext == 'doc' %}
                    <i class="fas fa-file-word"></i>  
                {% else %}
                    <i class="far fa-file"></i>
                {% endif %}
                    {{ post.get_file_name}}
            
                </a>
                {% endif %}
            </section>
            <hr>
        </div>
        <!-- Comments section-->
        <div id="comment-area">
        <section class="mb-5">
            <div class="card bg-light">
                <div class="card-body">
                    <!-- Comment form-->
                    <form class="mb-4"><textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea></form>
                    <!-- Comment with nested comments-->
                    <div class="d-flex mb-4">
                        <!-- Parent comment-->
                        <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                        <div class="ms-3">
                            <div class="fw-bold">Commenter Name</div>
                            If you're going to lead a space frontier, it has to be government; it'll never be private enterprise. Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
                            <!-- Child comment 1-->
                            <div class="d-flex mt-4">
                                <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                <div class="ms-3">
                                    <div class="fw-bold">Commenter Name</div>
                                    And under those conditions, you cannot establish a capital-market evaluation of that enterprise. You can't get investors.
                                </div>
                            </div>
                            <!-- Child comment 2-->
                            <div class="d-flex mt-4">
                                <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                <div class="ms-3">
                                    <div class="fw-bold">Commenter Name</div>
                                    When you put money directly to a problem, it makes a good headline.
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Single comment-->
                    <div class="d-flex">
                        <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                        <div class="ms-3">
                            <div class="fw-bold">Commenter Name</div>
                            When I look at the universe and all the ways the universe wants to kill us, I find it hard to reconcile that with statements of beneficence.
                        </div>
                    </div>
                </div>
            </div>
        </section>
        </div>
    </div>
{% endblock %}

Django/single_pages/templates/single_pages/about_me.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>개발자 Paul Pogaba</title>
</head>
<body>
    <nav>
        <a href="/blog/">Blog</a>
        <a href="/about_me/">About_me</a>
    </nav>

    <h1>HI, i'm Paul Pogaba man,</h1>
    <h2>이력</h2>
    <h3>Portfolio</h3>
    <h3>아직 공사중입니다.</h3>
</body>
</html>

Django/single_pages/templates/single_pages/landing.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>I am Paul Pogaba man,</title>
</head>
<body>
    <nav>
        <a href="/blog/">Blog</a>
        <a href="/about_me/">About_me</a>
    </nav>

    <h1>HI, i'm Paul Pogaba man,</h1>
    <h2>대문 페이지</h2>
    <h3>아직 만들지 않았슴둥</h3>
</body>
</html>